// primary: "#520a70",
// secondary: "#6383f0",
// accent: "#d695f5",
// background: "#09060a",
// text: "#c5fb79",

import Header from "./_components/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
